### ISSUE TITLE
сделайте, плз, возможность искать по загруженным символам.

### ISSUE THREAD

**Issue by dmitrychepel** [EugeneManushkin/CtagsSourceNavigator#2]
я виду это так.
после вызова какого-то пункта меню появляется окошко как в far ctags и в нём можно искать символы по всей загруженной базе.

**Comment by EugeneManushkin** [comment]
В меню editorа есть пункты
```Browse symbols in file
Browse symbols of class```
нужно добавить еще один:
```Browse symbols of entire repository```
Пункт будет показывать все символы из tags файла, в котором проиндексирован текущий открытый файл.

**Comment by dmitrychepel** [comment]
я б browse symbols of entire repo сделал не в редакторе (или не только в редакторе) но для главных окон тоже.

**Comment by EugeneManushkin** [comment]
Implemented in build_2.1.0.5
