### ISSUE TITLE
нужен case insensitive поиск

### ISSUE THREAD

**Issue by dmitrychepel** [EugeneManushkin/CtagsSourceNavigator#23]
нужен case insensitive поиск, тк порой тяжело вспомнить в каком кейзе был написан интерйейс. особенно важно при поиске по всему репо.

**Comment by EugeneManushkin** [comment]
Частично эта фича есть, она работает везде кроме "Search name in entire repository", это недоимплемент. Case insensitive поиск включается сниманием галочки "[ ] Case Sensitive filter" в конфигурации плагина. По умолчанию поиск чувствителен к регистру

**Comment by EugeneManushkin** [comment]
Implemented in build 2.1.0.26
