### ISSUE TITLE
(bug or feature lack?) Reload CURRENT file ONLY, - by menu command or automatically when the current editor file changed

### ISSUE THREAD

**Issue by dr-dba** [EugeneManushkin/CtagsSourceNavigator#79]
### Reload CURRENT file ONLY, by menu command or automatically when the current editor file changed.
Hello, i am trying to make use of it, looks good.
I also use Yalta, as i am working with Lua files, looks very good.
I am stumbled with some real life case scenario, and it looks like rather important for smooth using in development tasks.
see as the title says.
Lets consider this scenario (using FAR editor of course) :

1.) Programmer created new Lua file, or added some new functions in the opened file
2.) Programmer wants to be able to navigate to the functions
3.) .. and it can not, because the repository is not updated
4.) Programmer can not to reindex the entire repository each time he makes a change
5.) .. because it is too many mess to do, also from the convenice standpoint, and also from the performance overhead

Would not it be great, to detect file changes, and update correspondedly only the current file tags, kind of on the fly?
Has not to be asynchronous, because a single file scan is an easy quick task for the host resources.

Thank you!

**Comment by EugeneManushkin** [comment]
Hello @dr-dba!

The problem you described is expected behavior and I agree this is very inconvenient to re-index entire repository each time you made a small change in a file. Also if a user makes changes in a standalone file the only option to make these changes visible is to close the file and open it again.

Thank you for reporting the issue, I will work on it!

**Comment by EugeneManushkin** [comment]
Just released [build_2.1.0.71](https://github.com/EugeneManushkin/CtagsSourceNavigator/releases/tag/build_2.1.0.71) **withoud tests and guaranties**. I'll check the performance and decide whether plugin requires farther optimizations.
